/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2016-05-18 02:59:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class loginPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=windows-1256");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\r\n");
      out.write("\"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\" integrity=\"sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/style.css\">\r\n");
      out.write("<script src=\"<c:url value=\"resources/js/mailgun_validator.js\" />\"></script>\r\n");
      out.write("<script src=\"<c:url value=\"/resources/js/main.js\" />\"></script>\r\n");
      out.write(" <script src=\"//code.jquery.com/jquery-1.10.1.min.js\"></script>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js\"></script>\r\n");
      out.write("<!-- Latest compiled and minified JavaScript -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\" integrity=\"sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    \r\n");
      out.write("<script src=\"http://maps.googleapis.com/maps/api/js?key=AIzaSyCuK0lnSgOTVwMuBHXI22JfpSVfopATzqs\"></script>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\"\r\n");
      out.write("\tcontent=\"text/html; charset=windows-1256\">\r\n");
      out.write("\t<style>\r\n");
      out.write("    .success{color:#2ECC40;}\r\n");
      out.write("    .error{color:#FF4136;}\r\n");
      out.write("    .warning{color:#FF851B;}\r\n");
      out.write("    </style>\r\n");
      out.write("<title>Login Page</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"index.jsp\">ParkPal</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <ul class=\"nav navbar-nav\">\r\n");
      out.write("      <li class=\"active\"><a href=\"\">Login</a></li>\r\n");
      out.write("      <li class=\"active\"><a href=\"\">About Us</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("      <li><a href=\"register\"><span class=\"glyphicon glyphicon-user\"></span> Sign Up</a></li>\r\n");
      out.write("      <li><a href=\"loginPage\"><span class=\"glyphicon glyphicon-log-in\"></span> Login</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("  <center>\r\n");
      out.write("\t<h2>Member Login Page</h2>\r\n");
      out.write("\t<form action=\"LoginServlet\">\r\n");
      out.write("\r\n");
      out.write("\t\t<input type=\"text\" id=\"email\" class=\"subscribe-form form-control\" name=\"email\" placeholder=\"  Enter email here...\"/>\r\n");
      out.write("\t\t<div id=\"status\"></div>\r\n");
      out.write("<!-- \t\t<label for=\"email\">Email address</label><br>\r\n");
      out.write("        <input type=\"email\" name=\"email\" id=\"email\">\r\n");
      out.write("        <div id=\"status\"></div>\r\n");
      out.write(" -->\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<input type=\"text\" class=\"subscribe-form form-control\" name=\"password\" placeholder=\"  Enter password here...\" /> \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<input id=\"submit\" type=\"submit\" value=\"login\" class=\"btn btn-primary\">\r\n");
      out.write("\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("      // document ready\r\n");
      out.write("      $(function() {\r\n");
      out.write("\r\n");
      out.write("        // capture all enter and do nothing\r\n");
      out.write("        $('#email').keypress(function(e) {\r\n");
      out.write("          if(e.which == 13) {\r\n");
      out.write("            $('#email').trigger('focusout');\r\n");
      out.write("            return false;\r\n");
      out.write("          }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // capture clicks on validate and do nothing\r\n");
      out.write("        $(\"#validate_submit\").click(function() {\r\n");
      out.write("          return false;\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // attach jquery plugin to validate address\r\n");
      out.write("        $('#email').mailgun_validator({\r\n");
      out.write("          api_key: 'pubkey-83a6-sl6j2m3daneyobi87b3-ksx3q29',\r\n");
      out.write("          in_progress: validation_in_progress,\r\n");
      out.write("          success: validation_success,\r\n");
      out.write("          error: validation_error,\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      // while the lookup is performing\r\n");
      out.write("      function validation_in_progress() {\r\n");
      out.write("        $('#status').html(\"<img src='loading.gif' height='16'/>\");\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      // if email successfull validated\r\n");
      out.write("      function validation_success(data) {\r\n");
      out.write("        $('#status').html(get_suggestion_str(data['is_valid'], data['did_you_mean']));\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      // if email is invalid\r\n");
      out.write("      function validation_error(error_message) {\r\n");
      out.write("        $('#status').html(error_message);\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      // suggest a valid email\r\n");
      out.write("      function get_suggestion_str(is_valid, alternate) {\r\n");
      out.write("        if (is_valid) {\r\n");
      out.write("          var result = '<span class=\"success\">Address is valid.</span>';\r\n");
      out.write("          if (alternate) {\r\n");
      out.write("            result += '<span class=\"warning\"> (Though did you mean <em>' + alternate + '</em>?)</span>';\r\n");
      out.write("          }\r\n");
      out.write("          return result\r\n");
      out.write("        } else if (alternate) {\r\n");
      out.write("          return '<span class=\"warning\">Did you mean <em>' +  alternate + '</em>?</span>';\r\n");
      out.write("        } else {\r\n");
      out.write("          return '<span class=\"error\">Address is invalid.</span>';\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
